---
# tasks file for roles/docker_creation

  - name: installing required packages
    apt:
      name: "{{ item }}"
      state: latest
      update_cache: yes
    with_items: ["apt-transport-https","ca-certificates","curl","software-properties-common"]
    become: true
    ignore_errors: true

#  - name: "adding key"
#    command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
#    become: true

  - name: "ading key"
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    become: true
    ignore_errors: true
      
  - name: "adding repository"
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
      state: present
      filename: docker
    become: true

  - name: "installing docker"
    apt:
      name: "docker-ce"
      state: latest
      update_cache: yes
    become: true 
 
